[package]
name = "simplemoji"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1
incremental = true

[profile.release]
strip = true
lto = "thin"
panic = 'abort'
opt-level = 3
codegen-units = 1

[target.'cfg(not(target_family="wasm"))'.profile.dev.package."*"]
opt-level = 3

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"
emojis = "0.6.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
app_dirs2 = "2.5.5"
arboard = { version = "3.2.1", features = ["wayland-data-control"] }
dark-light = "1.0.0"
iced = "0.10.0"
iced_winit = { version = "0.10.0", features = ["application"] }
iced_aw = { version = "0.7.0", default-features = false, features = ["grid"] }
