[package]
name = "simplemoji"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1
incremental = true

[profile.release]
strip = true
lto = "thin"
panic = 'abort'
opt-level = 3
codegen-units = 1

[target.'cfg(not(target_family="wasm"))'.profile.dev.package."*"]
opt-level = 3

[dependencies]
log = "0.4.20"
env_logger = "0.10.0"
emojis = "0.6.1"
dark-light = "1.0.0"
display-info = "0.4.3"
device_query = "1.1.3"
iced_tiny_skia = "0.1.0"
iced = { version = "0.10.0", default-features = false, features = ["advanced"] }
iced_aw = { version = "0.7.0", default-features = false, features = ["grid"] }
clap = { version = "4.4.6", features = [
    "derive",
    "color",
    "env",
    "suggestions",
    "wrap_help",
] }
arboard = { version = "3.2.1", features = ["wayland-data-control"], default-features = false }
lazy_static = "1.4.0"
