name: Release
permissions:
  "contents": "write"

on:
  pull_request:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-prefixes-first-match: build-${{ runner.os }}-

      - name: Build nix
        run: nix build .#linux-x86_64-tar_gz

      - name: Move Bundle
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: .
        run: |
          cp result/*.tar.gz simplemoji-x86_64-unknown-linux-gnu.tar.gz

      - name: Generate a Changelog
        if: ${{ github.event_name != 'pull_request' }}
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --latest
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Release
        if: ${{ github.event_name != 'pull_request' }}
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, 'a') }}
          body: ${{ steps.git-cliff.outputs.content }}
          files: |
            simplemoji-x86_64-unknown-linux-gnu.tar.gz
